#ifndef UACPI_CONFIG_OVERRIDE_H
#define UACPI_CONFIG_OVERRIDE_H

#include <uacpi/helpers.h>
#include <uacpi/log.h>

#define UACPI_DEFAULT_LOG_LEVEL UACPI_LOG_INFO
#define UACPI_DEFAULT_LOOP_TIMEOUT_SECONDS 30
#define UACPI_DEFAULT_MAX_CALL_STACK_DEPTH 256
#define UACPI_PLAIN_LOG_BUFFER_SIZE 128
#define UACPI_STATIC_TABLE_ARRAY_LEN 16

#define UACPI_FORMATTED_LOGGING
#define UACPI_BAREBONES_MODE

#endif /* UACPI_CONFIG_OVERRIDE_H */
